### ISSUE TITLE
RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'mat2'

### ISSUE THREAD

**Issue by zhanghua7099** [MengHao666/Minimal-Hand-pytorch#22]
I try to run the `demo.py`, but get the following errors:

```
load model start
load model finished
start opencv
opencv finished
Traceback (most recent call last):
  File "demo.py", line 54, in <module>
    hand_verts, j3d_recon = mano(pose0, shape.float())
  File "/home/zhy/anaconda3/envs/minimal-hand-torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhy/anaconda3/envs/minimal-hand-torch/lib/python3.7/site-packages/manopth/manolayer.py", line 188, in forward
    self.th_posedirs, th_pose_map.transpose(0, 1)).permute(2, 0, 1)
RuntimeError: Expected object of backend CPU but got backend CUDA for argument #2 'mat2'
```

How to fix this bug?

**Comment by MengHao666** [comment]
Please refer to https://github.com/MengHao666/Minimal-Hand-pytorch/issues/11 for more information.
