### ISSUE TITLE
RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu

### ISSUE THREAD

**Issue by OutBreak-hui** [MengHao666/Minimal-Hand-pytorch#6]
Hello, how should this error be corrected

Traceback (most recent call last):
  File "D:/Work/writing/Minimal-Hand-pytorch-main/Minimal-Hand-pytorch-main/demo.py", line 60, in <module>
    hand_verts, j3d_recon = mano(pose0, shape.float())
  File "D:\software\anaconda\envs\yolov5\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Work\writing\Minimal-Hand-pytorch-main\Minimal-Hand-pytorch-main\manopth\manolayer.py", line 196, in forward
    root_trans = th_with_zeros(torch.cat([root_rot, root_j], 2))
RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu

**Comment by MengHao666** [comment]
It seems the  the `mano` , `pose0` and  `shape` are not on same device. Please check if your device is with cuda installed.

**Comment by OutBreak-hui** [comment]
> 看来的`mano`，`pose0`而 `shape`不是同一台设备上。请检查您的设备是否安装了cuda。

**Comment by bigbigbighead** [comment]
Hi！I met the similar problem like you. Why did we have this problem while others didn't and how did you sovle it? Thanks in advance!
