### ISSUE TITLE
I have encountered a difficulty, as shown below, I have not found a solution so far, please help me  

### ISSUE THREAD

**Issue by HaoWeiHsueh** [MengHao666/Minimal-Hand-pytorch#64]
Traceback (most recent call last):
  File "E:/PycharmProjects_SATI/Minimal-Hand-pytorch-main/demo.py", line 57, in <module>
    hand_verts, j3d_recon = mano(pose0, shape.float())
  File "E:\Software\Anaconda3\envs\minihand\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\PycharmProjects_SATI\Minimal-Hand-pytorch-main\manopth\manolayer.py", line 191, in forward
    self.th_posedirs, th_pose_map.transpose(0, 1)).permute(2, 0, 1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument mat2 in method wrapper_mm)

**Comment by MengHao666** [comment]
you might to find solutions in previous issues.---- Replied Message ***@***.***>Date04/29/2022 21:40 ***@***.***> ***@***.***>Subject[MengHao666/Minimal-Hand-pytorch] I have encountered a difficulty, as shown below, I have not found a solution so far, please help me (Issue #64)
Traceback (most recent call last):
File "E:/PycharmProjects_SATI/Minimal-Hand-pytorch-main/demo.py", line 57, in 
hand_verts, j3d_recon = mano(pose0, shape.float())
File "E:\Software\Anaconda3\envs\minihand\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
return forward_call(*input, **kwargs)
File "E:\PycharmProjects_SATI\Minimal-Hand-pytorch-main\manopth\manolayer.py", line 191, in forward
self.th_posedirs, th_pose_map.transpose(0, 1)).permute(2, 0, 1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument mat2 in method wrapper_mm)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/MengHao666/Minimal-Hand-pytorch/issues/64",
"url": "https://github.com/MengHao666/Minimal-Hand-pytorch/issues/64",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
