### ISSUE TITLE
RuntimeError  Expected all tensors to be on the same device

### ISSUE THREAD

**Issue by liushawn618** [MengHao666/Minimal-Hand-pytorch#79]
I have RuntimeError when I run python aik_pose.py. How can I solve it. I'd be really appreciate if someone could help me: 
Traceback (most recent call last):
  File "aik_pose.py", line 112, in <module>
    main(parser.parse_args())
  File "aik_pose.py", line 80, in main
    recon_eval(op_shapes, pre_j3ds, gt_j3ds, args.visualize, key_i)
  File "aik_pose.py", line 27, in recon_eval
    _, j3d_p0_ops = mano(pose0, op_shape)
  File "/home/lx/anaconda3/envs/minimal-hand-torch-v2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lx/anaconda3/envs/minimal-hand-torch-v2/lib/python3.7/site-packages/manopth/manolayer.py", line 188, in forward
    self.th_posedirs, th_pose_map.transpose(0, 1)).permute(2, 0, 1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_mm)

**Comment by liushawn618** [comment]
![image](https://github.com/MengHao666/Minimal-Hand-pytorch/assets/103125650/8272bdae-3ef0-4979-91a7-8440d2201eaa)

If you encounter the same problem, maybe you can try this in aik_pose.py
