### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by kishan1823** [MengHao666/Minimal-Hand-pytorch#9]
Hi, on running demo.py, i am getting error 

PS D:\KISHAN FILES\Minimal-Hand-pytorch-main> python demo.py
load model start
Traceback (most recent call last):
  File "demo.py", line 16, in <module>
    check_point = torch.load('new_check_point/ckp_detnet_83.pth', map_location=device)
  File "C:\Users\saisr\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\saisr\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\saisr\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'new_check_point/ckp_detnet_83.pth'

where is this .pth file 4?

**Comment by MengHao666** [comment]
Please look through the README.md carefully.
![image](https://user-images.githubusercontent.com/47114466/120917382-8c606180-c6e1-11eb-9159-780edd3272a2.png)
